name: my-first-github_action

on: push
jobs:
    first-jobs:
        runs-on: ubuntu-latest
        steps:
        - name: clone repository
          run: echo "git clone https//wgu.edu/academy"

        - name: performe software analysist security testing
          run: echo "sonarqube"
          

        - name: update system 
          run: sudo apt update -y

        - name: docker build image 
          run: echo "docker build -t my-app ."

        - name: docker push image
          run: echo "docker push "

        - name: delete docker images
          run: echo "docker rmi image id"
        - name: install docker
          run: apt install docker.io -y

        - name: run a docker container
          run: docker run -it --name jenkins -p 8080:8080 jenkins/jenkins:latest

        - name: check docker images
          run: docker ps -a
